Traceback (most recent call last):
  File "/home/llma/wzy/comorbidity/Codes/main_UKB_HGT.py", line 16, in <module>
    fit_transform(data=HGData,
  File "/home/llma/wzy/comorbidity/Codes/train.py", line 44, in fit_transform
    encoder = models.Encoder(node_types=list(data.node_types),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llma/wzy/comorbidity/Codes/models.py", line 44, in __init__
    self.convs.append(EdgeAwareHGTConv(
                      ^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'EdgeAwareHGTConv.EdgeAwareHGTConv(...)'?
